// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"context"
	"sync"

	computev1 "cloud.google.com/go/compute/apiv1"
	"github.com/googleapis/gax-go/v2"
	computepb "google.golang.org/genproto/googleapis/cloud/compute/v1"
)

// Ensure, that disksClientMock does implement disksClient.
// If this is not the case, regenerate this file with moq.
var _ disksClient = &disksClientMock{}

// disksClientMock is a mock implementation of disksClient.
//
// 	func TestSomethingThatUsesdisksClient(t *testing.T) {
//
// 		// make and configure a mocked disksClient
// 		mockeddisksClient := &disksClientMock{
// 			ListFunc: func(contextMoqParam context.Context, listDisksRequest *computepb.ListDisksRequest, callOptions ...gax.CallOption) *computev1.DiskIterator {
// 				panic("mock out the List method")
// 			},
// 			SetLabelsFunc: func(contextMoqParam context.Context, setLabelsDiskRequest *computepb.SetLabelsDiskRequest, callOptions ...gax.CallOption) (*computev1.Operation, error) {
// 				panic("mock out the SetLabels method")
// 			},
// 		}
//
// 		// use mockeddisksClient in code that requires disksClient
// 		// and then make assertions.
//
// 	}
type disksClientMock struct {
	// ListFunc mocks the List method.
	ListFunc func(contextMoqParam context.Context, listDisksRequest *computepb.ListDisksRequest, callOptions ...gax.CallOption) *computev1.DiskIterator

	// SetLabelsFunc mocks the SetLabels method.
	SetLabelsFunc func(contextMoqParam context.Context, setLabelsDiskRequest *computepb.SetLabelsDiskRequest, callOptions ...gax.CallOption) (*computev1.Operation, error)

	// calls tracks calls to the methods.
	calls struct {
		// List holds details about calls to the List method.
		List []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// ListDisksRequest is the listDisksRequest argument value.
			ListDisksRequest *computepb.ListDisksRequest
			// CallOptions is the callOptions argument value.
			CallOptions []gax.CallOption
		}
		// SetLabels holds details about calls to the SetLabels method.
		SetLabels []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
			// SetLabelsDiskRequest is the setLabelsDiskRequest argument value.
			SetLabelsDiskRequest *computepb.SetLabelsDiskRequest
			// CallOptions is the callOptions argument value.
			CallOptions []gax.CallOption
		}
	}
	lockList      sync.RWMutex
	lockSetLabels sync.RWMutex
}

// List calls ListFunc.
func (mock *disksClientMock) List(contextMoqParam context.Context, listDisksRequest *computepb.ListDisksRequest, callOptions ...gax.CallOption) *computev1.DiskIterator {
	if mock.ListFunc == nil {
		panic("disksClientMock.ListFunc: method is nil but disksClient.List was just called")
	}
	callInfo := struct {
		ContextMoqParam  context.Context
		ListDisksRequest *computepb.ListDisksRequest
		CallOptions      []gax.CallOption
	}{
		ContextMoqParam:  contextMoqParam,
		ListDisksRequest: listDisksRequest,
		CallOptions:      callOptions,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(contextMoqParam, listDisksRequest, callOptions...)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//     len(mockeddisksClient.ListCalls())
func (mock *disksClientMock) ListCalls() []struct {
	ContextMoqParam  context.Context
	ListDisksRequest *computepb.ListDisksRequest
	CallOptions      []gax.CallOption
} {
	var calls []struct {
		ContextMoqParam  context.Context
		ListDisksRequest *computepb.ListDisksRequest
		CallOptions      []gax.CallOption
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// SetLabels calls SetLabelsFunc.
func (mock *disksClientMock) SetLabels(contextMoqParam context.Context, setLabelsDiskRequest *computepb.SetLabelsDiskRequest, callOptions ...gax.CallOption) (*computev1.Operation, error) {
	if mock.SetLabelsFunc == nil {
		panic("disksClientMock.SetLabelsFunc: method is nil but disksClient.SetLabels was just called")
	}
	callInfo := struct {
		ContextMoqParam      context.Context
		SetLabelsDiskRequest *computepb.SetLabelsDiskRequest
		CallOptions          []gax.CallOption
	}{
		ContextMoqParam:      contextMoqParam,
		SetLabelsDiskRequest: setLabelsDiskRequest,
		CallOptions:          callOptions,
	}
	mock.lockSetLabels.Lock()
	mock.calls.SetLabels = append(mock.calls.SetLabels, callInfo)
	mock.lockSetLabels.Unlock()
	return mock.SetLabelsFunc(contextMoqParam, setLabelsDiskRequest, callOptions...)
}

// SetLabelsCalls gets all the calls that were made to SetLabels.
// Check the length with:
//     len(mockeddisksClient.SetLabelsCalls())
func (mock *disksClientMock) SetLabelsCalls() []struct {
	ContextMoqParam      context.Context
	SetLabelsDiskRequest *computepb.SetLabelsDiskRequest
	CallOptions          []gax.CallOption
} {
	var calls []struct {
		ContextMoqParam      context.Context
		SetLabelsDiskRequest *computepb.SetLabelsDiskRequest
		CallOptions          []gax.CallOption
	}
	mock.lockSetLabels.RLock()
	calls = mock.calls.SetLabels
	mock.lockSetLabels.RUnlock()
	return calls
}
