// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"sync"

	computepb "google.golang.org/genproto/googleapis/cloud/compute/v1"
)

// Ensure, that diskIteratorMock does implement diskIterator.
// If this is not the case, regenerate this file with moq.
var _ diskIterator = &diskIteratorMock{}

// diskIteratorMock is a mock implementation of diskIterator.
//
// 	func TestSomethingThatUsesdiskIterator(t *testing.T) {
//
// 		// make and configure a mocked diskIterator
// 		mockeddiskIterator := &diskIteratorMock{
// 			NextFunc: func() (*computepb.Disk, error) {
// 				panic("mock out the Next method")
// 			},
// 		}
//
// 		// use mockeddiskIterator in code that requires diskIterator
// 		// and then make assertions.
//
// 	}
type diskIteratorMock struct {
	// NextFunc mocks the Next method.
	NextFunc func() (*computepb.Disk, error)

	// calls tracks calls to the methods.
	calls struct {
		// Next holds details about calls to the Next method.
		Next []struct {
		}
	}
	lockNext sync.RWMutex
}

// Next calls NextFunc.
func (mock *diskIteratorMock) Next() (*computepb.Disk, error) {
	if mock.NextFunc == nil {
		panic("diskIteratorMock.NextFunc: method is nil but diskIterator.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//     len(mockeddiskIterator.NextCalls())
func (mock *diskIteratorMock) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}
